# This workflow checks the quality of PRs (not their commits)
# This includes:
#   - The PR title follows conventional commits

name: Check PR

on:
  workflow_call:
    inputs:
    secrets:
      REVIEWER_TOKEN:
        required: true

jobs:
  conventional_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEWER_TOKEN }}
