name: Version bump
description: Fetches the current version and calculates the next version
inputs:
  release_type:
    description: Which type of release is this?
    type: choice
    options:
      - patch
      - minor
      - major
    default: patch
outputs:
  current_tag:
    description: The version before any increments, with a tag prefix. (ex "v1.2.3")
    value: ${{ steps.current.outputs.tag }}
  current_number:
    description: The version before any increments. (ex "1.2.3")
    value: ${{ steps.current.outputs.number }}
  next_tag:
    description: The version after any increments, with a tag prefix. (ex "v1.2.3")
    value: ${{ steps.next.outputs.tag }}
  next_number:
    description: The version after any increments. (ex "1.2.3")
    value: ${{ steps.next.outputs.number }}
runs:
  using: "composite"
  steps:
      - name: Install semver-cli
        shell: bash
        run: |-
          go install github.com/maykonlf/semver-cli/cmd/semver@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Get current version
        id: current
        shell: bash
        run: |-
          echo "CURRENT=$(semver get release)"
          echo "tag=$CURRENT" >> "$GITHUB_OUTPUT"
          echo "number=$(echo $CURRENT | sed 's/v//')" >> "$GITHUB_OUTPUT"
      - name: Get next version
        id: next
        shell: bash
        env:
          FLAG: ${{ inputs.release_type == 'patch' && 'release' || inputs.release_type}}
        run: |-
          semver up "$FLAG"
          echo "NEXT=$(semver get release)"
          echo "tag=$NEXT" >> "$GITHUB_OUTPUT"
          echo "number=$(echo $NEXT | sed 's/v//')" >> "$GITHUB_OUTPUT"
      - name: Prepare commit
        shell: bash
        run: |-
          git add .semver.yaml
          git commit -m "update .semver.yaml"
      - name: Document
        run: |-
          {
            echo "Versions numbers:"
            echo "Current: ${{ steps.current.outputs.number }}"
            echo "Next: ${{ steps.next.outputs.number }}"
            echo "Versions tags:"
            echo "Current: ${{ steps.current.outputs.tag }}"
            echo "Next: ${{ steps.next.outputs.tag }}"
          } >> "$GITHUB_STEP_SUMMARY"
