# This workflow sets all the labels in the provided repositories to a set of shared labels.

name: Sync Labels

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: ${{ secrets.REPOSITORY_LIST }}
